---
- name: Set permission for dropbear directory
  file:
    path: "{{ config_path }}/etc/dropbear/"
    mode: "700"

- name: Set permission for authorized_keys
  file:
    path: "{{ config_path }}/etc/dropbear/authorized_keys"
    mode: "600"
