---

wireless_profiles:
  - name: disable
    devices:
      - radio: 11a_standard
        disabled: true
      - radio: 11g_standard
        disabled: true
      - radio: 11a_mesh
        disabled: true

  - name: mesh_default
    devices:
      - radio: 11a_standard
        legacy_rates: false
        country: DE
      - radio: 11g_standard
        legacy_rates: false
        country: DE
      - radio: 11a_mesh
        legacy_rates: false
        country: DE

    ifaces:
      - mode: mesh
        mesh_id: Mountain-Mesh
        radio: [11a_standard, 11g_standard, 11a_mesh]
        mcast_rate: 12000
        mesh_fwding: 0
        ifname_hint: mesh

all__channel_assignments_11a_standard__to_merge:
  default: "36-20"

all__channel_assignments_11g_standard__to_merge:
  default: "13-20"

all__channel_assignments_11a_mesh__to_merge:
  default: "36-20"
